--- # Start

--- # change port
server:
  port: 8080

--- # Thymeleaf
spring:
  thymeleaf:
    cache: false # ?? ?? reload
    prefix: file:src/main/resources/templates # classpath:/templates
    suffix: .html

--- # mariadb
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/anirest
    username: test
    password: test

--- #
spring:
  jpa:
    hibernate:
      ddl-auto: update #update
    properties:
      hibernate:
        show_sql : true
        format_sql: true